CREATE TABLE CONTACT(
  ID INT GENERATED BY DEFAULT AS IDENTITY
                                         (START WITH 1, INCREMENT BY 1) NOT NULL
, FIRST_NAME VARCHAR(60) NOT NULL
, LAST_NAME  VARCHAR(40) NOT NULL
, BIRTH_DATE DATE
, PRIMARY KEY (ID)
);
ALTER TABLE CONTACT ADD UNIQUE (FIRST_NAME, LAST_NAME);

----------------------------------------------------------------------------------------------------------------------
CREATE TABLE CONTACT_TEL_DETAIL (
ID INT GENERATED BY DEFAULT AS IDENTITY
                                         (START WITH 1, INCREMENT BY 1) NOT NULL
, CONTACT_ID INT NOT NULL
, TEL_TYPE VARCHAR(40) NOT NULL
, TEL_NUMBER VARCHAR(40) NOT NULL
, PRIMARY KEY (ID)
);

ALTER TABLE CONTACT_TEL_DETAIL ADD UNIQUE (CONTACT_ID, TEL_TYPE, TEL_NUMBER);
ALTER TABLE CONTACT_TEL_DETAIL ADD FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID);
);


-- ALTER TABLE <tablename>
--     ADD [CONSTRAINT <constraintname>] FOREIGN KEY (<column list>)
--     REFERENCES <exptablename> (<column list>)
--     [ON {DELETE | UPDATE} {CASCADE | SET DEFAULT | SET NULL}];
-- Adds a foreign key constraint to the table, using the same constraint syntax as when the foreign key is specified in
-- a table definition.